### ISSUE TITLE
DKD+reviewKD有样例.yaml配置吗？代码里面也没看到有结合的地方?

### ISSUE THREAD

**Issue by leo19850812** [megvii-research/mdistiller#10]

**Comment by Zzzzz1** [comment]
是指DKD+ReviewKD在MS-COCO上的实验吗？我们也刚刚发现这个遗漏，结合方式就是同时使用dkd loss和reviewkd loss，后面会更新相关的代码和config。

**Comment by twmht** [comment]
@Zzzzz1 

請問在 train ReviewKD 的時候，teacher net 是的 bn 是用 training mode 還是 eval mode?

**Comment by Zzzzz1** [comment]
> @Zzzzz1
> 
> 請問在 train coco with ReviewKD 的時候，teacher net 是的 bn 是用 training mode 還是 eval mode? 從 code 上面看不出有切換到 eval mode

训练所有网络时bn都是eval mode，在Distiller的[基类](https://github.com/megvii-research/mdistiller/blob/master/mdistiller/distillers/_base.py)里面写好了teacher.eval()

**Comment by ufestkc** [comment]
> @Zzzzz1
> 
> 請問在 train coco with ReviewKD 的時候，teacher net 是的 bn 是用 training mode 還是 eval mode? 從 code 上面看不出有切換到 eval mode

请问意思是用教师给学生蒸馏训练的时候，教师要用eval mode吗
