### ISSUE TITLE
ignore index in DKD

### ISSUE THREAD

**Issue by Chic-J** [megvii-research/mdistiller#11]
Hi！Thanks for the great work.
But I found something wrong in dkd_loss codes.
when the dataset has **ignore index**, `RuntimeError: cuda runtime error (59) : device-side triggered at ...` problem will occur in the **_get_gt_mask** and **_get_other_mask** functions.
i wonder how to fix it? thanks.

**Comment by Zzzzz1** [comment]
Could you show the example code for ignore-index？It seems like the label is larger than the num_classes.
