### ISSUE TITLE
关于数据增强

### ISSUE THREAD

**Issue by peiyingxin** [megvii-research/mdistiller#13]
请问是否使用过数据增强去提升模型精度呢？例如mixup等？
另外关于使用 timm 的 mixup ，target shape 会变化，314000*1 >> 314*1000  这样的话这个 mask 该怎么去计算呢？
谢谢~

**Comment by Zzzzz1** [comment]
mixup之后一张图片应该会有两个带权重的label，此时可以把TCKD定义为KL(pt1, pt2, pnt)，NCKD则是KL(pi; i != t1,t2)，如果mixup+dkd一起用的话，可能需要重写一下DKD的代码。

**Comment by peiyingxin** [comment]
请问是否尝试过 DKD + dataAug 的效果吗？数据增强对 DKD 精度提升是否有效？作者做过类似的消融实验吗？

**Comment by Zzzzz1** [comment]
没有尝试过+strong aug的实验setting，不过数据增强和DKD的涨点应该是互不冲突的。Strong aug下使用DKD的话，可能TCKD需要适当增强，因为训练数据难度变高了。
