### ISSUE TITLE
关于图像分割

### ISSUE THREAD

**Issue by huweiv** [megvii-research/mdistiller#14]
作者，您好，请问DKD能否用于图像分割蒸馏的任务呢

**Comment by Zzzzz1** [comment]
你好，理论上来讲是可行的，因为分割任务也可以看成是像素级别的分类，那么就可以使用dkd来进行蒸馏。

**Comment by coallar** [comment]
请问，语义分割上的处理是真么实现的呀？可以分享一下吗

**Comment by Zzzzz1** [comment]
> 请问，语义分割上的处理是真么实现的呀？可以分享一下吗

这个我们没有实现过。如果baseline是像素级的KL-Div来做loss的话，可以尝试改成像素级的dkd loss看看效果。
