### ISSUE TITLE
About validation

### ISSUE THREAD

**Issue by fairy149** [megvii-research/mdistiller#16]
Hello, I downloaded your code, want to see the effect of the code, I downloaded the pre-training weight file to the specified folder as required, running 
python3 tools/eval.py -m resnet32x4 # resnet32x4 on cifar100
The result of the occurrence is
![XP_~~0{2CKKK_USNTAK}6SR](https://user-images.githubusercontent.com/101486709/177288226-b225fa92-bcad-4ea9-894c-6baaad7993e2.png)
And when I run
python3 tools/eval.p -m resnet8x4 -c download_ckpts/dkd_resnet8x4 
No corresponding file is displayed
I don't know why this is happening, and I want to know what kind of results should be obtained and look forward to your reply

**Comment by Zzzzz1** [comment]
- The validation result is 79.42%(as the final value shows).
- please download the checkpoint file first following the README, then run ```... -c download_ckpts/dkd_resnet8x4```.
