### ISSUE TITLE
DKD可否用于其他领域

### ISSUE THREAD

**Issue by DonMuv** [megvii-research/mdistiller#17]
DKD看起来是对全连接层输出的logits进行蒸馏的，请问是否可以应用在没有全连接层的网络中，但看起来需要通道对齐操作是吗

**Comment by Zzzzz1** [comment]
这个是指feature蒸馏吗？feature蒸馏的方法是不适合dkd的，但是可以考虑试试利用CAM等手段决定对应各个类别对应channel的attention来帮助提升效果。
