### ISSUE TITLE
Train a single model on cifar 100

### ISSUE THREAD

**Issue by IfuChan** [megvii-research/mdistiller#20]
Hi, is there a way to train a single model like resnet32x4 on cifar 100 on this repo? Want to train the models from scratch without using the pretrained models.

**Comment by Zzzzz1** [comment]
Please refer to this config：https://github.com/megvii-research/mdistiller/blob/master/configs/cifar100/vanilla.yaml
(change the "student" to "resnet32x4")

**Comment by IfuChan** [comment]
Thanks for replying. 
I tried that, the issue is after training, when using the DKD strat to train the student, I get Missing keys and Unexpected keys error on train.py on load_state_dict. The model I trained has keys module.student.conv1.weights ... and the missing ones are conv1.weights etc.

**Comment by Zzzzz1** [comment]
There would be two types of models saved(*, *student). The ones with 'student' in their name are suitable as pretrain models.

**Comment by IfuChan** [comment]
Worked, thank you.
Also, wanted to ask why are the size of the models with 'student' in their names smaller than the ones without it? Since here we are using Vanilla, so no distillation is happening so I do not understand why it would be smaller?
![Screenshot 2022-07-24 144810](https://user-images.githubusercontent.com/74062350/180639637-bdda9bff-e22f-48e1-b6ec-ff0ae9dcef02.jpg)

**Comment by Zzzzz1** [comment]
We save all the parameters(of the student, the teacher, and the connector/contrastive memory..) for the checkpoints. Vanilla models are also saved with the teacher's parameters(useless), and we will consider to fixing that.

**Comment by IfuChan** [comment]
Understood, thank you very much.
