### ISSUE TITLE
Different Dataset on DKD transforms.Resize error

### ISSUE THREAD

**Issue by IfuChan** [megvii-research/mdistiller#21]
Hi, I was trying to use a different dataset with two classes and image size 1024 in this repo, however, I get an error _RuntimeError: Function AddmmBackward returned an invalid gradient at index 1 - got [2, 256] but expected shape compatible with [2, 4096]_  when I use transforms.Resize(128) in the dataloader transforms function. However if I use transforms.Resize(32), the pipeline works. Could you help me out here.
![Screenshot 2022-08-04 182334](https://user-images.githubusercontent.com/74062350/182853483-6120b01a-28ba-4eef-8c64-992fb143d9d4.jpg)

**Comment by Zzzzz1** [comment]
If using higher resolution data as the input, you need to change the base model first. Changing the image size to 224x224 and using the ImageNet base models would achieve good performance. Hope my response could be useful for you.
