### ISSUE TITLE
运行train.py找不到mdistiller.models模块

### ISSUE THREAD

**Issue by Xglbrilliant** [megvii-research/mdistiller#26]
没有进行任何更改，但是出现这种情况：
![image](https://user-images.githubusercontent.com/95476150/196112873-78711fd6-40ad-432f-b9e0-cd4065c9ab0e.png)
请问一下这是什么原因呢？期待您的解答，谢谢您！

**Comment by Zzzzz1** [comment]
确认有运行过安装命令吗？
```bash
sudo python3 setup.py develop
```
以及python版本是否是3.6

**Comment by Xglbrilliant** [comment]
谢谢您的解答，我的版本是3.9，我不知道这是否会造成影响，我去试一下，谢谢！

**Comment by Zzzzz1** [comment]
> 谢谢您的解答，我的版本是3.9，我不知道这是否会造成影响，我去试一下，谢谢！

3.9可能需要这样才能安装成功：
```bash
sudo python3 setup.py develop --user
```

**Comment by Xglbrilliant** [comment]
您好，在更换python3.6之后还是一样的问题，请问一下可能是什么原因呢？

**Comment by Zzzzz1** [comment]
可以手动查看sys.path中是否包含mdistiller的路径。
如果没有的话，在代码中手动加入路径可能可以解决。
```python
import sys
sys.path.append(path_to_mdistiller)
```

**Comment by wzq12322** [comment]
请问一下这个sys.path是一个文件吗？怎么找不到啊
