### ISSUE TITLE
how to understand nckd loss ?

### ISSUE THREAD

**Issue by Tongfengyu** [megvii-research/mdistiller#27]
![捕获](https://user-images.githubusercontent.com/82866148/200990261-08ff3e1d-0f20-479b-9333-2e7096fd7987.PNG)
I think the nckd loss is kl loss between teacher and student prediction among nckd output probability, whose shape should be (n,c-1),like Algorithm 1, the Pseudo code of DKD in your paper.
But, why you compute like this , is this equivalent? Could you give a  further explanation, thanks!

**Comment by Zzzzz1** [comment]
See issue #1 .
