### ISSUE TITLE
安装了mdistiller之后运行train.py找不到mdistiller模块

### ISSUE THREAD

**Issue by wzq12322** [megvii-research/mdistiller#28]
![image](https://user-images.githubusercontent.com/102721490/204255799-c97d0b6f-b899-4dd2-a174-ceb6ab4d08cd.png)
![image](https://user-images.githubusercontent.com/102721490/204255979-5cdfc790-ea30-4c82-a097-0583c5db3318.png)
成功安装了0.1版本但是还是显示没有找到模块，请问一下这个怎么解决

**Comment by Zzzzz1** [comment]
可以参考 issue #26 
确认下python版本是否是3.6，不是的话可能需要```sudo python3 setup.py develop --user```进行安装。
如果仍有问题，可以在代码中用sys手动导入mdistiller的path。

**Comment by wzq12322** [comment]
> 可以参考 issue #26 确认下python版本是否是3.6，不是的话可能需要`sudo python3 setup.py develop --user`进行安装。 如果仍有问题，可以在代码中用sys手动导入mdistiller的path。

谢谢您的回答，我的python版本是3.6版本，添加了mdistiller的路径之后还是提示没有这个模块，其余的代码我没有修改过，请问一下是什么原因呢？
![image](https://user-images.githubusercontent.com/102721490/204468875-e77dbaf8-42f0-423f-ab54-cb1916734541.png)
![image](https://user-images.githubusercontent.com/102721490/204468925-31106532-d143-4609-abdc-27ae38a3bb07.png)

**Comment by Zzzzz1** [comment]
这个是指在py运行的代码处添加sys.path，具体就是写python文件或者终端打开python的时候，先sys.path.append再尝试import mdistiller

**Comment by wzq12322** [comment]
> 这个是指在py运行的代码处添加sys.path，具体就是写python文件或者终端打开python的时候，先sys.path.append再尝试import mdistiller

谢谢您的解答！加入了sys之后程序可以正常运行了
![image](https://user-images.githubusercontent.com/102721490/204756282-24dd4f3b-4d4b-4965-8107-c36ea9007aa1.png)
![image](https://user-images.githubusercontent.com/102721490/204756327-a69d037f-783a-4cd4-8bb5-5df8dce6d7d7.png)
