### ISSUE TITLE
How is the acc reported calculated?

### ISSUE THREAD

**Issue by TinyTigerPan** [megvii-research/mdistiller#30]
Hello, I want to know how the acc in paper calculated? 
In paper, I found `All results are the average over 5/3 trials on CIFAR100/ImageNet`, and I want to know whether the acc is the best acc or something else.
Many thanks!

**Comment by Zzzzz1** [comment]
Our paper reports the best accuracies among epochs. As for large-scale datasets such as MS-COCO and ImageNet, the best accuracy is pretty much the same as the accuracy of the last epoch.

**Comment by TinyTigerPan** [comment]
Thanks.
