### ISSUE TITLE
关于reviewkd+dkd 的 yaml 配置问题 

### ISSUE THREAD

**Issue by alexchungio** [megvii-research/mdistiller#31]
大佬，reviewkd+dkd 目标检测的yaml 文什么时候会更新呢，看到关闭的问题列表中提到会更新，手动催更。

**Comment by Zzzzz1** [comment]
近期会尽快更新

**Comment by Zzzzz1** [comment]
代码和config已更新 83c7d41d4be49feab8741a3e1da765df96a09aab 

> 大佬，reviewkd+dkd 目标检测的yaml 文什么时候会更新呢，看到关闭的问题列表中提到会更新，手动催更。

**Comment by alexchungio** [comment]
> 代码和config已更新 [83c7d41](https://github.com/megvii-research/mdistiller/commit/83c7d41d4be49feab8741a3e1da765df96a09aab)
> 
> > 大佬，reviewkd+dkd 目标检测的yaml 文什么时候会更新呢，看到关闭的问题列表中提到会更新，手动催更。

> 代码和config已更新 [83c7d41](https://github.com/megvii-research/mdistiller/commit/83c7d41d4be49feab8741a3e1da765df96a09aab)
> 
> > 大佬，reviewkd+dkd 目标检测的yaml 文什么时候会更新呢，看到关闭的问题列表中提到会更新，手动催更。

感谢
