### ISSUE TITLE
Question about the alpha weight in ImageNet training

### ISSUE THREAD

**Issue by ZaberKo** [megvii-research/mdistiller#32]
First, thanks for the great work. We find the alpha is set to 0.5 in the paper for ImageNet, but the config files in the code: `configs/imagenet/r34_r18/dkd.yaml`, `configs/imagenet/r50_mv1/dkd.yaml` seem to use alpha=1 (the default value in `cfg.py`). What is the real alpha value used in the report?

**Comment by Zzzzz1** [comment]
Sorry for the mistake. We use alpha=0.5 in the reports. However, the results on ImageNet are insensitive with different alpha values. We tested the experiment configs in this codebase and achieved almost the same results.
