### ISSUE TITLE
安装成功detectron2后运行detection的DKD报错AttributeError: USE_FED_LOSS

### ISSUE THREAD

**Issue by Muke6** [megvii-research/mdistiller#33]
![微信截图_20230224114939](https://user-images.githubusercontent.com/89955551/221087471-ed63ef2a-1309-43b5-8232-7104f95e2925.png)

**Comment by Zzzzz1** [comment]
这个问题和使用的detectron2的版本有关。用v0.6之前的版本不会报这个错，或者在config里面加上对应的选项。

**Comment by CaoQiZhi** [comment]
请问解决了吗，小白一只，遇到了同样的问题QAQ
