### ISSUE TITLE
关于MobileNet-v2在ImageNet的top-1 acc问题

### ISSUE THREAD

**Issue by lxy-94** [megvii-research/mdistiller#4]
您好，您在论文“**Decoupled Knowledge Distillation**”的Table 9中提到MobileNet-v2在ImageNet的top-1 acc为68.87%，这个指标是您训练出的结果么？因为MobileNet-v2的官方提供的指标为72.0%，您为何不基于72.0%的精度继续做kd的相关论证呢？希望您可以解答我的疑惑。

**Comment by Zzzzz1** [comment]
我们follow了ReviewKD论文中的结果，跑DKD时用的也是相同setting，这样方便直接对比。PS：MobileNet-V2在ImageNet上的训练超参数和大多数网络都不同，比如epoch、learning rate、scheduler等，蒸馏的setting则是follow了ResNet的标准setting，点数差距可能主要来自这里

**Comment by lxy-94** [comment]
> 我们follow了ReviewKD论文中的结果，跑DKD时用的也是相同setting，这样方便直接对比。PS：MobileNet-V2在ImageNet上的训练超参数和大多数网络都不同，比如epoch、learning rate、scheduler等，蒸馏的setting则是follow了ResNet的标准setting，点数差距可能主要来自这里

好的，谢谢。

**Comment by hunto** [comment]
@Zzzzz1 Hi，您好，麻烦检查一下你们paper中的ResNet50-MobileNetV2的setting是否对比正确，表格里的其余方法实质上都是使用的MobileNetV1 model，这一点可以从以下几篇paper中验证：

ReviewKD：估计是paper里cite错了，虽然cite的是mbv2，但是实际上开源代码里用的是mbv1，参见：https://github.com/dvlab-research/ReviewKD/blob/master/ImageNet/models/mobilenet.py  
OFD：paper里报的结果和cite的paper都是mbv1

如果是你们的student模型用错了，麻烦对表格进行一下更正吧。最近已经发现几篇最新的paper错误使用了mbv2的模型来对比之前mbv1的方法了。不胜感激！
