### ISSUE TITLE
DKD代码问题

### ISSUE THREAD

**Issue by xiaoxusanheyi** [megvii-research/mdistiller#47]
你好作者：我想问一下DKD部分的代码具体在哪里那个位置，可否给指出来。 可以详细一点多少行开始到多少行结束。
祝好！

**Comment by ufestkc** [comment]
https://github.com/megvii-research/mdistiller/tree/master/mdistiller/distillers

不知道你是不是找的这个

**Comment by xiaoxusanheyi** [comment]
该目录下的DKD.py文件里的代码就是解耦知识蒸馏(DKD)的代码是吧！

**Comment by ufestkc** [comment]
对，主要的几个函数，缝起来就行了
