### ISSUE TITLE
Do you apply AutoAugment in Table 6?

### ISSUE THREAD

**Issue by mzhaoshuai** [megvii-research/mdistiller#5]
Hi, thx for your wonderful work!

I am concerned that whether you use AutoAugment is Table 6

![image](https://user-images.githubusercontent.com/22476764/165079322-962ac225-e69e-4dca-9c15-39d50861a9e8.png)

**Comment by Zzzzz1** [comment]
Experiments in this table don't use AutoAugment(Only Table.2 in Sec3 use this strategy to increase the "difficulty" of training data).

**Comment by mzhaoshuai** [comment]
Thx for your reply!
