### ISSUE TITLE
Can't reproduce the accuracy.

### ISSUE THREAD

**Issue by YujieZheng99** [megvii-research/mdistiller#7]
I have tried many times, but I couldn't reproduce the experimental results in the paper(76.32%)(res32x4_res8x4)
The results of five rounds of experiments are:76.20,75.80,75.89,75.85,76.15
The environment is the same as that in readme.md: python 3.6, torch1.9.0, torchvision0.10.0
The GPU of my device is 2080Ti and the operating system is Ubuntu 20.04
Is there anything I have overlooked?

**Comment by Zzzzz1** [comment]
Here are more details about our experiments: 
The GPU number for CIFAR-100 is set as 1. 
The operating system is Ubuntu 18.04.

Our experiments could achieve 76.5%(for the best) and 75.9%(for the worst).
BTW, what about reproducing results of other experiments? If most of the results are ok, maybe it's just the random seed that matters....

**Comment by 1292224662** [comment]
@Zzzzz1 Is the test_acc reported in the paper the best_acc during the whole training(i.e. max(test_acc) for all epoches)?

 I guess @zhyjbig used the acc of last epoch for comparison and the paper used the best_acc and that's the cause of the gap.
