### ISSUE TITLE
Can you provide pre training models for teachers and students on Imagenet？

### ISSUE THREAD

**Issue by 773041642** [megvii-research/mdistiller#9]
This paper is excellent and the code is very standard.But my own training model is very time-consuming in ImageNet, so can you provide them to us？
Thanks very much!

**Comment by Zzzzz1** [comment]
The pre-trained models for the students can be attached: https://github.com/megvii-research/mdistiller/releases/tag/checkpoints
And the pre-trained teachers are from torchvision.
